-- 1) Buat tabel ucapan.
create table if not exists public.birthday_wishes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.birthday_wishes enable row level security;

-- 2) Pastikan pengunjung biasa hanya boleh INSERT.
drop policy if exists "Anyone can submit birthday wishes" on public.birthday_wishes;
create policy "Anyone can submit birthday wishes"
on public.birthday_wishes
for insert
to anon
with check (true);

-- 3) Ganti EMAIL_KAMU dengan email yang dipakai untuk akun admin Supabase.
-- Hanya email tersebut yang boleh membaca daftar ucapan.
drop policy if exists "Only birthday owner can read wishes" on public.birthday_wishes;
create policy "Only birthday owner can read wishes"
on public.birthday_wishes
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'EMAIL_KAMU');

-- Tidak ada policy update/delete untuk pengunjung.
